set PROJECT_HOME=%CD%
set ANT_HOME=%PROJECT_HOME%\PROJECTS-BASE\apache-ant-1.8.2
set JAVA_HOME=%PROJECT_HOME%\PROJECTS-BASE\jdk1.7.0_03
set HSQL_HOME=%PROJECT_HOME%\PROJECTS-EXT-LIB\hsqldb-2.2.5\hsqldb\lib
set PATH=%JAVA_HOME%\bin;%ANT_HOME%\bin;%PATH%;