
package org.ahp.vinavidai.services.quiz;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-30T16:34:35.344-05:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "NoSuchQuiz", targetNamespace = "http://quiz.services.vinavidai.ahp.org/")
public class NoSuchQuizException extends Exception {
    
    private org.ahp.vinavidai.services.quiz.NoSuchQuiz noSuchQuiz;

    public NoSuchQuizException() {
        super();
    }
    
    public NoSuchQuizException(String message) {
        super(message);
    }
    
    public NoSuchQuizException(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchQuizException(String message, org.ahp.vinavidai.services.quiz.NoSuchQuiz noSuchQuiz) {
        super(message);
        this.noSuchQuiz = noSuchQuiz;
    }

    public NoSuchQuizException(String message, org.ahp.vinavidai.services.quiz.NoSuchQuiz noSuchQuiz, Throwable cause) {
        super(message, cause);
        this.noSuchQuiz = noSuchQuiz;
    }

    public org.ahp.vinavidai.services.quiz.NoSuchQuiz getFaultInfo() {
        return this.noSuchQuiz;
    }
}
