package org.ahp.vinavidai.services.quiz;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-30T16:34:35.416-05:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "QuizServiceService", 
                  wsdlLocation = "WEB-INF/CONFIG/WEB-SERVICES/WSDL/QuizService.wsdl",
                  targetNamespace = "http://quiz.services.vinavidai.ahp.org/") 
public class QuizServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://quiz.services.vinavidai.ahp.org/", "QuizServiceService");
    public final static QName QuizServicePort = new QName("http://quiz.services.vinavidai.ahp.org/", "QuizServicePort");
    static {
        URL url = null;
        try {
            url = new URL("WEB-INF/CONFIG/WEB-SERVICES/WSDL/QuizService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QuizServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "WEB-INF/CONFIG/WEB-SERVICES/WSDL/QuizService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QuizServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QuizServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuizServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public QuizServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public QuizServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public QuizServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns QuizService
     */
    @WebEndpoint(name = "QuizServicePort")
    public QuizService getQuizServicePort() {
        return super.getPort(QuizServicePort, QuizService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuizService
     */
    @WebEndpoint(name = "QuizServicePort")
    public QuizService getQuizServicePort(WebServiceFeature... features) {
        return super.getPort(QuizServicePort, QuizService.class, features);
    }

}
