package org.ahp.vinavidai.services.quiz;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-30T16:34:35.401-05:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://quiz.services.vinavidai.ahp.org/", name = "QuizService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QuizService {

    @WebResult(name = "getQuizInfoByNameResponse", targetNamespace = "http://quiz.services.vinavidai.ahp.org/", partName = "parameters")
    @WebMethod
    public GetQuizInfoByNameResponse getQuizInfoByName(
        @WebParam(partName = "parameters", name = "getQuizInfoByNameRequest", targetNamespace = "http://quiz.services.vinavidai.ahp.org/")
        GetQuizInfoByNameRequest parameters
    ) throws NoSuchQuizException;
}
