
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.ahp.vinavidai.services.quiz;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-30T16:34:35.376-05:00
 * Generated source version: 2.6.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "QuizServiceService",
                      portName = "QuizServicePort",
                      targetNamespace = "http://quiz.services.vinavidai.ahp.org/",
                      wsdlLocation = "",
                      endpointInterface = "org.ahp.vinavidai.services.quiz.QuizService")
                      
public class QuizServiceImpl implements QuizService {

    private static final Logger LOG = Logger.getLogger(QuizServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see org.ahp.vinavidai.services.quiz.QuizService#getQuizInfoByName(org.ahp.vinavidai.services.quiz.GetQuizInfoByNameRequest  parameters )*
     */
    public org.ahp.vinavidai.services.quiz.GetQuizInfoByNameResponse getQuizInfoByName(GetQuizInfoByNameRequest parameters) throws NoSuchQuizException    { 
        LOG.info("Executing operation getQuizInfoByName");
        System.out.println( parameters );
        try {
            GetQuizInfoByNameResponse lGetQuizInfoByNameResponse = new GetQuizInfoByNameResponse();
            Quiz lQuiz = new Quiz();
            lQuiz.setQuizId( 1 );
            lQuiz.setQuizName( "One" );
            lQuiz.setQuizDescription( "One Description " + parameters.getName() );
            lGetQuizInfoByNameResponse.getReturn().add( lQuiz  );
            return lGetQuizInfoByNameResponse;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new NoSuchQuizException("NoSuchQuizException...");
    }

}
